#!/usr/bin/env bash

set -euo pipefail

function ctrl_c() {
    echo "INTERRUPTED"
}

function print() {
    osascript -e "display notification \"${2} (exit=${3})\" with title \"$1\""
}


function usage() {
cat << EOT
usage: $0 [file] [command]
EOT
}

function main(){
    if [ "$#" -lt 3 ]; then
        usage
        exit 1
    fi
    
    WATCHED="$1"
    shift
    COMMAND="$@"

    trap ctrl_c INT
    
    while true; do
        echo "$(date) - Watching ${WATCHED}"
        fswatch -1 -t "$WATCHED" &
        wait $!
        
        if [[ $? != 0 ]]; then
            break;
        fi;
        
        set +e
        eval "$COMMAND"
        local COMMAND_RES=$?
        set -e

        print "$WATCHED" "$COMMAND" "$COMMAND_RES"
    done
}

main "$@"

