#!/usr/bin/env bash

set -e

trap ctrl_c INT

function ctrl_c() {
    echo "INTERRUPTED"
}

function print() {
    osascript -e "display notification \"$1\" with title \"fswatch_notify\""
}

function fail() {
    print "Execution error" "$1"
}

function done() {
    print "$1 exited with code $2"
}

WATCHED='src/main/asciidoc/index.adoc'
COMMAND='mvn asciidoc:process-doc'

while true; do
    fswatch -1 -t "$WATCHED" &
    wait $!
    
    if [[ $? != 0 ]]; then
        break;
    fi;

    set +e 
    mvn asciidoc:process-doc
    if [[ $? != 0 ]]; then
        fail "$COMMAND"
    fi
    set -e

    break
    
done
